services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSP (Server-Ausgang)
      - "1935:1935" # RTMP
      - "8888:8888" # HLS (Browser-tauglich!)
      - "8889:8889" # WebRTC (Niedrige Latenz)
      - "9997:9997" # API Port access from extern
    volumes:
      - ./mediamtx.yml:/mediamtx.yml

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"   # MQTT
      #- "9001:9001"   # MQTT über WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  db:
    image: postgres:15-alpine
    container_name: microservice_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init_sentra.sql:/docker-entrypoint-initdb.d/init.sql
      - ./day_meanings_export.csv:/docker-entrypoint-initdb.d/day_meanings_export.csv
      - ./liveview_channels.csv:/docker-entrypoint-initdb.d/liveview_channels.csv
    ports:
      - "5432:5432" # Optional, falls Zugriff von außen benötigt

volumes:
  pg-data:

# docker compose down -v  (-v löschen der Datenbank)
# docker compose up -d
# docker compose logs db
# docker logs mediamtx
# docker-compose logs -f mediamtx
# docker compose exec db psql -U dbuser -d sentra

# docker exec -it mosquitto mosquitto_sub -h localhost -t "#" -v-v
# indoor/sensor/climate {"temp":21.60,"hum":45.98,"pres":1028.83}