services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=authdb
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: node_container
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/authdb
      - JWT_SECRET=mein_geheimnis
      - REFRESH_SECRET=mein_super_geheimnis_fuer_refresh
      - PORT=3000
      - NODE_ENV=development
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db

volumes:
  pg-data:

# docker compose down -v  (-v löschen der Datenbank)
# docker compose up -d
# docker compose logs db  bzw. app
# docker compose exec db psql -U user -d authdb