services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-ralfhgw}/sentra-authserver:${IMAGE_TAG:-latest}
    container_name: node_container
    restart: unless-stopped
    ports:
      - "${AUTH_SERVER_PORT}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV:-production}
      - AUTH_DEFAULT_USER_STATUS=${AUTH_DEFAULT_USER_STATUS:-pending}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
    depends_on:
      - db

volumes:
  pg-data:

# docker compose down -v  (-v löschen der Datenbank)
# docker compose up -d
# docker compose logs db  bzw. app
# docker compose exec db psql -U user -d authdb
# UPDATE users SET status = 'active' WHERE id = '37d128eb-93e9-478d-a56c-3ca6d0712a0a';
