name: Deploy sentra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NEXT_PUBLIC_AUTH_HOST: ${{ secrets.NEXT_PUBLIC_AUTH_HOST }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm ci
        working-directory: sentra/

      - name: Build
        run: npm run build
        working-directory: sentra/


      - name: Deploy to Server
        if: success()
        env:
           SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        run: |
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deploy@webschere.de "
           cd ~/sentra
           git reset --hard
           git pull origin main
           cd sentra
           ls -la
           npm ci
           export NODE_OPTIONS='--max-old-space-size=4096'
           npm run build
           pm2 restart sentra || pm2 start npm --name sentra -- run start
           "