name: Deploy sentra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NEXT_PUBLIC_AUTH_HOST: ${{ secrets.NEXT_PUBLIC_AUTH_HOST }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install sentra dependencies
        run: npm ci
        working-directory: sentra/

      - name: Build sentra
        run: npm run build
        working-directory: sentra/


      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload build + services to server
        if: success()
        env:
         SSH_OPTS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        run: |
          ssh $SSH_OPTS -i ~/.ssh/id_rsa deploy@webschere.de "
          mkdir -p /data/sentra_build
          mkdir -p ~/sentra/sentra
          rm -rf /data/sentra_build/.next
          rm -rf /data/sentra_build/node_modules
          ln -sf /data/sentra_build/.next ~/sentra/sentra/.next
          ln -sf /data/sentra_build/node_modules ~/sentra/sentra/node_modules
          "
          rsync -az --delete -e "ssh $SSH_OPTS -i ~/.ssh/id_rsa" sentra/.next/ deploy@webschere.de:/data/sentra_build/.next/
          rsync -az -e "ssh $SSH_OPTS -i ~/.ssh/id_rsa" sentra/package.json sentra/package-lock.json sentra/next.config.mjs deploy@webschere.de:~/sentra/sentra/
          rsync -az --delete -e "ssh $SSH_OPTS -i ~/.ssh/id_rsa" authServer/ deploy@webschere.de:~/sentra/authServer/
          rsync -az -e "ssh $SSH_OPTS -i ~/.ssh/id_rsa" microservice/ deploy@webschere.de:~/sentra/microservice/

      - name: Install runtime deps and restart services
        if: success()
        env:
          SSH_OPTS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        run: |
            ssh $SSH_OPTS -i ~/.ssh/id_rsa deploy@webschere.de "
            mkdir -p /data/sentra_build
            ln -sf /data/sentra_build/.next ~/sentra/sentra/.next
            ln -sf /data/sentra_build/node_modules ~/sentra/sentra/node_modules

            cd ~/sentra/sentra && npm ci --omit=dev
            cd ~/sentra/authServer && npm ci --omit=dev

            pm2 restart sentra || pm2 start npm --name sentra --prefix ~/sentra/sentra -- run start
            "